### PR TITLE
Testing/revoke torch for 312

### PR DESCRIPTION
**Pull request by jlnav**
Dunno why the badge removals made it into this branch.

Watching status of: https://github.com/Libensemble/libensemble/actions/runs/6793309244

Triggered via: `gh workflow run libEnsemble-complete-CI --ref testing/revoke_torch_for_312`

### CODE REVIEW

**Review by jmlarson1 — APPROVED** [review]

**Comment by jlnav** [comment]
https://github.com/Libensemble/libensemble/actions/runs/6801007731

**Comment by jlnav** [comment]
https://github.com/Libensemble/libensemble/actions/runs/6801206668

**Comment by jlnav** [comment]
https://github.com/Libensemble/libensemble/actions/runs/6801686540

**Comment by jlnav** [comment]
https://github.com/Libensemble/libensemble/actions/runs/6801845349

**Comment by jlnav** [comment]
https://github.com/Libensemble/libensemble/actions/runs/6802219262

**Comment by jlnav** [comment]
https://github.com/Libensemble/libensemble/actions/runs/6802431040

**Comment by jlnav** [comment]
https://github.com/Libensemble/libensemble/actions/runs/6802763365

**Pull request merged**
