### PR TITLE
Rearrange specs.py libE_specs fields to match libE_specs.rst

### PR DESCRIPTION
**Pull request by jlnav**
And rearrange components of tcp_mgr. py for macos support

### CODE REVIEW

**Comment by jmlarson1** [comment]
I'm guessing that it wasn't possible to group the fields like we had before:

https://libensemble--986.org.readthedocs.build/en/986/data_structures/libE_specs.html

**Comment by jlnav** [comment]
Nope, unfortunately. Although, if we had sub-classes or dictionaries for these common groups, e.g. `DirectorySpecs`, `TCPConfig`, `ResourceSpecs`, etc,  they'd be grouped in the docs. Then such an API may resemble:

```
from libensemble.specs import LibeSpecs, ResourceSpecs

libE_specs = LibeSpecs(
   comms = "local",
   nworkers = 16,
   resources = ResourceSpecs(
      num_resource_sets = 32,
      zero_resource_workers = [1]
   )
)

**Comment by jmlarson1** [comment]
Let's list `comms` as optional before pulling in.

**Comment by shuds13** [comment]
Makes mpi comms optional.

**Review by jmlarson1 — APPROVED** [review]

**Pull request merged**
