### PR TITLE
Debugging when work is not a dictionary

### PR DESCRIPTION
**Pull request by jmlarson1**

### CODE REVIEW

**Comment by jmlarson1** [comment]
Is this the correct way to raise this error?

**Comment by jmlarson1** [comment]
There are various intermittent errors. For two 

https://github.com/Libensemble/libensemble/actions/runs/3903957476/jobs/6669062308
https://github.com/Libensemble/libensemble/actions/runs/3903957476/jobs/6669061312

we will add prints to the tests themselves. For the other intermittent error:
https://github.com/Libensemble/libensemble/actions/runs/3902762108/jobs/6666218712
we have to add a print to `worker.py`.

**Review by jlnav — APPROVED** [review]
Looks good, probably also good to add an additional internal comment to revisit before release. shouldn't need to wait for tests to pass again on pushing that commit

**Comment by jmlarson1** [comment]
> Looks good, probably also good to add an additional internal comment to revisit before release. shouldn't need to wait for tests to pass again on pushing that commit

I'm hoping that https://github.com/Libensemble/libensemble/issues/960 will suffice.

**Pull request merged**
