### PR TITLE
Configuration options for libE_stats.txt

### PR DESCRIPTION
**Pull request by shuds13**
Todo:

Terminology/decisions:
- Decide on terminology for supplying a prefix/precedent/wrapper to application in register_app.
- OR whether we should not have that option - or make it all in app.
- Decide on app_cmd variable name
- Decide if sub-dictionary is best for stats file configuration options - currently using one - stats_fmt (and naming)

Ensure that changes consistent with Balsam executor.

Add/Update a regression (functionality) test to use the stats options and include a sim that runs multiple tasks.

Need to ensure consistent with any scripts that read - at least when using defaults.

Options  include:
- task timing (summary or start/end)
- resource sets

Possible options:
- change resolution of timing output (e.g. options to have whole seconds for longer runs)
- space for sim_ids (integer width)
- could remove the excess gen/sim, but could affect backward compatibility - scripts etc...

### CODE REVIEW

**Comment by shuds13** [comment]
Example with task summaries (3 tasks) and rsets (only one each) on laptop

```
Worker     1: Gen no     1: gen Time: 0.000 Start: 2022-06-03 23:46:56.721 End: 2022-06-03 23:46:56.721  Status: Not set rsets: [0]
Worker     3: sim_id     2: sim Time: 0.460 Start: 2022-06-03 23:46:56.725 End: 2022-06-03 23:46:57.185  Status: Completed Task 0: 0.132 Task 1: 0.151 Task 2: 0.161 rsets: [2]
Worker     1: sim_id     0: sim Time: 0.816 Start: 2022-06-03 23:46:56.724 End: 2022-06-03 23:46:57.540  Status: Completed Task 0: 0.243 Task 1: 0.263 Task 2: 0.292 rsets: [0]
Worker     1: sim_id     4: sim Time: 0.650 Start: 2022-06-03 23:46:57.541 End: 2022-06-03 23:46:58.191  Status: Completed Task 0: 0.191 Task 1: 0.212 Task 2: 0.232 rsets: [0]
Worker     2: sim_id     1: sim Time: 1.662 Start: 2022-06-03 23:46:56.725 End: 2022-06-03 23:46:58.387  Status: Completed Task 0: 0.676 Task 1: 0.475 Task 2: 0.495 rsets: [1]
Worker     3: sim_id     3: sim Time: 1.650 Start: 2022-06-03 23:46:57.187 End: 2022-06-03 23:46:58.837  Status: Completed Task 0: 0.485 Task 1: 0.636 Task 2: 0.515 rsets: [2]
Worker     1: sim_id     5: sim Time: 0.720 Start: 2022-06-03 23:46:58.192 End: 2022-06-03 23:46:58.912  Status: Completed Task 0: 0.242 Task 1: 0.221 Task 2: 0.242 rsets: [0]
Worker     3: sim_id     7: sim Time: 0.719 Start: 2022-06-03 23:46:58.838 End: 2022-06-03 23:46:59.557  Status: Completed Task 0: 0.262 Task 1: 0.232 Task 2: 0.212 rsets: [2]
Worker     2: sim_id     6: sim Time: 1.295 Start: 2022-06-03 23:46:58.388 End: 2022-06-03 23:46:59.683  Status: Completed Task 0: 0.424 Task 1: 0.403 Task 2: 0.454 rsets: [1]
```

Version with full start/end for each task is quite long!

**Comment by shuds13** [comment]
bbox="tight" is deprecated option.

MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "bbox" which is no longer supported as of 3.3 and will become an error in 3.6

**Comment by shuds13** [comment]
With my new test that checks libE_stats.txt I have identified a difference in behaviour between mpi4py and local comms, and also I think a bug.
The difference is that local comms closes the log files between libE calls, and when you next log it works but it overwrites (both ensemble.log and libE_stats.txt) and only leaves output from the last libE call.

If I dont close the logs its okay, but there is no way to know if you are last libE call (we have no init/finalize). Alt. maybe close but set up to append, but then it would append if one left over from a previous run - or maybe we could say if logger already set, append - I will see if that works. Then again, looks like only local comms closes it anyway.

The bug seems to be, I'm still checking this - that when using fork the workers start logging directly after the first libE call. I think this is because the manager logger of this name is setup by the time of the second libE call and so when forks workers - they get the manager filehandler! Hopefully, I can fix this.

**Comment by shuds13** [comment]
Now appends libE_stats.txt - e.g. 

```
Manager     : Starting ensemble at: 2022-06-23 10:34:08.285
Worker     1: Gen no     1: gen Time: 0.000 Start: 2022-06-23 10:34:08.287 End: 2022-06-23 10:34:08.287 Status: Not set
Worker     3: sim_id     2: sim Time: 0.120 Start: 2022-06-23 10:34:08.289 End: 2022-06-23 10:34:08.409 Status: Completed
Worker     1: sim_id     0: sim Time: 0.291 Start: 2022-06-23 10:34:08.289 End: 2022-06-23 10:34:08.580 Status: Completed
Worker     2: sim_id     1: sim Time: 0.483 Start: 2022-06-23 10:34:08.289 End: 2022-06-23 10:34:08.772 Status: Completed
Worker     1: sim_id     4: sim Time: 0.239 Start: 2022-06-23 10:34:08.581 End: 2022-06-23 10:34:08.820 Status: Completed
Worker     3: sim_id     3: sim Time: 0.582 Start: 2022-06-23 10:34:08.410 End: 2022-06-23 10:34:08.992 Status: Completed
Worker     2: sim_id     5: sim Time: 0.239 Start: 2022-06-23 10:34:08.773 End: 2022-06-23 10:34:09.012 Status: Completed
Worker     3: sim_id     7: sim Time: 0.239 Start: 2022-06-23 10:34:08.994 End: 2022-06-23 10:34:09.233 Status: Completed
Worker     1: sim_id     6: sim Time: 0.461 Start: 2022-06-23 10:34:08.822 End: 2022-06-23 10:34:09.283 Status: Completed
Manager     : Exiting ensemble at: 2022-06-23 10:34:09.284 Time Taken: 0.999
Manager     : Starting ensemble at: 2022-06-23 10:34:09.285
Worker     1: Gen no     1: gen Time: 0.000 Start: 2022-06-23 10:34:09.286 End: 2022-06-23 10:34:09.286 Status: Not set
Worker     2: sim_id     1: sim Time: 0.098 Start: 2022-06-23 10:34:09.288 End: 2022-06-23 10:34:09.386 Status: Completed
Worker     1: sim_id     0: sim Time: 0.270 Start: 2022-06-23 10:34:09.287 End: 2022-06-23 10:34:09.557 Status: Completed
Worker     3: sim_id     2: sim Time: 0.370 Start: 2022-06-23 10:34:09.288 End: 2022-06-23 10:34:09.658 Status: Completed
Worker     2: sim_id     3: sim Time: 0.289 Start: 2022-06-23 10:34:09.387 End: 2022-06-23 10:34:09.676 Status: Completed
Worker     1: sim_id     4: sim Time: 0.198 Start: 2022-06-23 10:34:09.559 End: 2022-06-23 10:34:09.757 Status: Completed
Worker     2: sim_id     6: sim Time: 0.208 Start: 2022-06-23 10:34:09.677 End: 2022-06-23 10:34:09.885 Status: Completed
Worker     1: sim_id     7: sim Time: 0.219 Start: 2022-06-23 10:34:09.759 End: 2022-06-23 10:34:09.978 Status: Completed
Worker     3: sim_id     5: sim Time: 0.431 Start: 2022-06-23 10:34:09.659 End: 2022-06-23 10:34:10.090 Status: Completed
Manager     : Exiting ensemble at: 2022-06-23 10:34:10.090 Time Taken: 0.805
```

**Review by jlnav — APPROVED** [review]

**Review by jmlarson1 — APPROVED** [review]

**Pull request merged**
