### PR TITLE
Feature/enforce first comms

### PR DESCRIPTION
**Pull request by jlnav**
Please let me know if I'm possibly missing any edge-cases or possibilities for simplification.

Helps address #1331

### CODE REVIEW

**Comment by jlnav** [comment]
Currently displaying UserWarnings upon trying to overwrite comms. It would be easy enough to change these to ValueErrors.

**Review by jmlarson1 — APPROVED** [review]

**Review by shuds13 — CHANGES_REQUESTED** [review]
Issues:

`test_1d_sampling_no_comms_given.py` is failing on local comms. We need to decide what should happen here.

The above test, and my original test code, has no `sampling.is_manager` True when run with MPI. Notice the print and save file does not happen.

**Comment by jlnav** [comment]
> Issues:
> 
> `test_1d_sampling_no_comms_given.py` is failing on local comms. We need to decide what should happen here.
> 
> The above test, and my original test code, has no `sampling.is_manager` True when run with MPI. Notice the print and save file does not happen.

It's failing because with parse_args=False, it defaults to an empty LibeSpecs() (MPI). Then we try updating the LibeSpecs with nworkers (local), so as decided, it fails.

Perhaps we can remove the test. I think that fail-condition is covered by the `test_ensemble_prevent_comms_overwrite` and `test_local_comms_without_nworkers` unit tests. I'd only keep it for coverage purposes if the execution somehow proceeds _BEYOND_ where the unit tests already test for intentional ValueErrors

**Comment by shuds13** [comment]
- [ ] We also need to check, no examples in docs or anywhere that would not work with this.

**Comment by shuds13** [comment]
> It's failing because with parse_args=False, it defaults to an empty LibeSpecs() (MPI). Then we try updating the LibeSpecs with nworkers (local), so as decided, it fails.

I think the correct behavior is to ignore nworkers when MPI is decided so the test works either way. I can change this.

**Comment by shuds13** [comment]
> Perhaps we can remove the test. I think that fail-condition is covered by the `test_ensemble_prevent_comms_overwrite` and `test_local_comms_without_nworkers` unit tests. I'd only keep it for coverage purposes if the execution somehow proceeds _BEYOND_ where the unit tests already test for intentional ValueErrors

We definitely want a full parallel test on this. We are looking at making sure is_manager and nworkers are correctly set.

**Review by shuds13 — APPROVED** [review]
I think this is ready now.

**Pull request merged**
