### PR TITLE
Feature/register apps

### PR DESCRIPTION
**Pull request by shuds13**
Add registration of applications by name to Executor.

### CODE REVIEW

**Comment by shuds13** [comment]
> Looks good. Executor overview (`docs/executor/overview.rst`) may need some small updates.

Good point. I am updating.

**Comment by shuds13** [comment]
This also makes me think about argument naming here. For I have used 'name' for register_calc, and 'app_name' in submit. @jlnav @jmlarson1 Any preferences here?

Calling script::

    exctr.register_calc(full_path='/path/to/my/exe', name='forces_app')

User sim func::

    task = exctr.submit(app_name='forces_app', num_procs=8, app_args='input.txt',
                        stdout='out.txt', stderr='err.txt')

Not to mention the function should really be register_app.

**Comment by jlnav** [comment]
> This also makes me think about argument naming here. For I have used 'name' for register_calc, and 'app_name' in submit. @jlnav @jmlarson1 Any preferences here?

I think both parameters could be ``app_name``, but if this correction is made now, it should be done in such a way so that it isn't a breaking change.

I also support renaming ``register_calc`` to ``register_app``, but maybe this should be saved for before a major release.

**Comment by shuds13** [comment]
The name/app_name is a new arg, so not a breaking change either way. So just which one is preferred. I think they should be the same. The register_calc/register_app would be a breaking change, so I won't be making that now.

**Comment by jlnav** [comment]
> The name/app_name is a new arg, so not a breaking change either way. So just which one is preferred. I think they should be the same. The register_calc/register_app would be a breaking change, so I won't be making that now.

Ah, right. I like ``app_name``, it's more descriptive without being much longer.

**Pull request merged**
