### PR TITLE
Feature/libe env script shell

### PR DESCRIPTION
**Pull request by shuds13**
Launch user environment scripts in shell.

### CODE REVIEW

**Comment by n01r** [comment]
I tried this for my case and I got this error message now:
```
[0]  2024-08-01 15:36:29,802 libensemble.manager (ERROR): ---- Received error message from worker 1 ----
[0]  2024-08-01 15:36:29,803 libensemble.manager (ERROR): Message: IsADirectoryError: [Errno 21] Is a directory: '/pscratch/sd/m/mgarten/superfacilities_IFE/2024/010_scan_TODs_and_positions_3cppwl_optimas_after_fix/exploration/evaluations/sim0000'
[0]  2024-08-01 15:36:29,803 libensemble.manager (ERROR): Traceback (most recent call last):
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/libensemble/worker.py", line 405, in run
    response = self._handle(Work)
               ^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/libensemble/worker.py", line 351, in _handle
    calc_out, persis_info, calc_status = self._handle_calc(Work, calc_in)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/libensemble/worker.py", line 269, in _handle_calc
    out = calc(calc_in, Work)
          ^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/libensemble/utils/runners.py", line 40, in run
    return self._result(calc_in, Work["persis_info"], Work["libE_info"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/libensemble/utils/runners.py", line 34, in _result
    return self.f(*args)
           ^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/optimas/sim_functions.py", line 87, in run_template_simulation
    step_specs["analysis_func"](task.workdir, libE_output[0])
  File "/pscratch/sd/m/mgarten/superfacilities_IFE/2024/010_scan_TODs_and_positions_3cppwl_optimas_after_fix/analyze_histogram_1D.py", line 29, in analyze_hist1D
    df = pd.read_csv(filepath,delimiter=r'\s+')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/pscratch/sd/m/mgarten/superfacilities_IFE/2024/010_scan_TODs_and_positions_3cppwl_optimas_after_fix/exploration/evaluations/sim0000'

[0]  2024-08-01 15:36:29,814 libensemble.libE (ERROR): Manager exception raised .. aborting ensemble:
[0]  2024-08-01 15:36:29,815 libensemble.libE (ERROR): Dumping ensemble history with 0 sims evaluated:
Traceback (most recent call last):
  File "/pscratch/sd/m/mgarten/superfacilities_IFE/2024/010_scan_TODs_and_positions_3cppwl_optimas_after_fix/run_grid_scan.py", line 90, in <module>
    exp.run()
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/optimas/explorations/base.py", line 212, in run
    history, persis_info, flag = libE(
                                 ^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/pydantic/validate_call_decorator.py", line 60, in wrapper_function
    return validate_call_wrapper(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/pydantic/_internal/_validate_call.py", line 96, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/libensemble/libE.py", line 262, in libE
    return libE_funcs[libE_specs.get("comms", "mpi")](
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/libensemble/libE.py", line 509, in libE_local
    return manager(
           ^^^^^^^^
  File "/global/cfs/cdirs/m4546/mgarten/sw/perlmutter/gpu/venvs/warpx-gpu/lib/python3.11/site-packages/libensemble/libE.py", line 310, in manager
    raise LoggedException(*e.args, "See error details above and in ensemble.log") from None
libensemble.manager.LoggedException: ('Received error message from worker 1', "IsADirectoryError: [Errno 21] Is a directory: '/pscratch/sd/m/mgarten/superfacilities_IFE/2024/010_scan_TODs_and_positions_3cppwl_optimas_after_fix/exploration/evaluations/sim0000'", 'See error details above and in ensemble.log')
```

**Comment by n01r** [comment]
Sorry, I got another error but it looks like this one is on my side so I deleted my comment.

**Review by jmlarson1 — APPROVED** [review]
Do we want a test of the `shell=use_shell` capability for `launcher.launch`?

**Comment by jlnav** [comment]
This time around, I'm not sure there's that much to test since the added keyword is just passed through to subprocess. And the code specifying the parameter is naturally covered.

**Review by jlnav — APPROVED** [review]

**Pull request merged**
