### PR TITLE
Proposed changes to make alloc support more intuitive

### PR DESCRIPTION
**Pull request by jmlarson1**
This is what I was trying to describe in the talk today. I like the current level of `try... except... ` content in the example alloc_f.

### CODE REVIEW

**Comment by jlnav** [comment]
As we discussed, I don't mind the changes for ``points_by_priority()``, ``all_returned()``, etc. I'll update this with additional resource considerations as I encounter them...

Two points I've thought about, not necessarily related to resources:

1. Now that we're considering passing each of ``H``, ``H_fields`` and ``H_rows`` into ``sim_work()`` and ``gen_work()``, would it be a bad idea to combine those? e.g.:

   `sim_work(self, Work, wid, H_fields, H_rows, persis_info, H=None, **libE_info)`

   could be:

   ``sim_work(self, Work, wid, H_sel, persis_info, **libE_info)``

   where ``H_sel = H[H_fields][H_rows]`` in the ``alloc_f``.

   Would this simplify ``_check_work_order()`` and ``_send_work_order()`` in the manager?

2. Passing ``Work`` into ``sim_work()`` and ``gen_work()`` to be updated in-place based ``wid`` keys is very C-like when those functions could return ``Work`` dictionary entries instead, e.g.:

   ``Work[wid] = sim_work(wid, H_sel, persis_info.get(wid))``

**Comment by shuds13** [comment]
Okay, taking these points one at a time.

For the modified code, I guess its okay just to pass H into sim_work. I'm not sure about the use_resource_sets option. Currently it would only make sense if resource_sets is a gen_out - otherwise  its not in H - unless we use a .get(resource_sets,1). But if the users has already had to think about it, to add it as a gen_out - do we need an option also. Perhaps if you want a quick way to turn it on and off? But then what is the default? It would also become an inactive option is disable_resource_manger=True.

**Comment by jmlarson1** [comment]
We can (and should) assert that `resource_sets` is a `gen_out` if `use_resource_sets` is True.

**Comment by shuds13** [comment]
But if resource_sets is a gen_specs['out'], then you also need to add use_resource_sets=True ?

The only reason I can see, and maybe its a good reason, is if you want to have a gen that sets resource_sets, but say you want to ignore it.

**Comment by jmlarson1** [comment]
> But if resource_sets is a gen_specs['out'], then you also need to add use_resource_sets=True ?

I think of this as the opposite. If `use_resource_sets` is True, the user must supply them. If (by happenstance) they have a `gen_specs['out']` field that is called `resource_sets`, but `use_resources_sets` is False (or unset), then we'd ignore them.

**Comment by shuds13** [comment]
Okay, but I could compare with with 'priority' where we dont have a use_priority option, we just look if the field is there.

**Comment by jlnav** [comment]
> I think of this as the opposite. If `use_resource_sets` is True, the user must supply them. If (by happenstance) they have a `gen_specs['out']` field that is called `resource_sets`, but `use_resources_sets` is False (or unset), then we'd ignore them.

Hm, yeah, I'd think a user that explicitly specifies ``'resource_sets'`` as a gen_out wants to take advantage, automatically, of resource set features

**Comment by shuds13** [comment]
>     1. `sim_work(self, Work, wid, H_sel, persis_info, **libE_info)`
>        where `H_sel = H[H_fields][H_rows]` in the `alloc_f`.

If I'm reading this right, H_sel would contain the actual data. I guess its a view but  it would need to go with a single send, which needs revisiting comms. So I would keep work as metadata, and its something that you might want to look at. If it contained the data rows, that can sometimes be very large. 

Points 2 - Yes I probably prefer this style. I did consider returning a success value previously, but if we are happy flanking try/except on sim/gen work then we probably wont be doing that.

**Comment by jlnav** [comment]
> If I'm reading this right, H_sel would contain the actual data. I guess its a view but it would need to go with a single send, which needs revisiting comms. So I would keep work as metadata, and its something that you might want to look at. If it contained the data rows, that can sometimes be very large.

Fair enough!

Another question: Following an ``InsufficientFreeResources`` exception, why ``break`` instead of ``continue``?

**Comment by shuds13** [comment]
> Another question: Following an `InsufficientFreeResources` exception, why `break` instead of `continue`? Are other work-units for either the sim or gen also unlikely to succeed, even if they (for sims) potentially request smaller resource sets?

They will be requesting the same resource sets, because it will keep trying to schedule the same work. Generally each loop is dealing with either sims or gens (or only doing a gen once all work is done). Let me know if you spot an exception.

I have an alternative for preemptive algorithm, but I've not pushed it. In that case there is an inner loop that will go though the available work units until either enough resources is found or has gone through all work generated.

**Comment by jmlarson1** [comment]
This is being completed by #664

**Pull request closed without merging**
