### PR TITLE
Refactor/reorganize forces

### PR DESCRIPTION
**Pull request by jlnav**
Addresses #759 .

Pulls into feature/balsam7 since this also refactors the new test in that PR.

TODO: Test new version of balsam forces with Theta.

### CODE REVIEW

**Comment by shuds13** [comment]
Path to forces in define_apps.py will need to be ...forces_app/forces.x

Maybe balsam_forces -> forces_balsam (and same for funcx) to be consistent with others naming.

**Comment by shuds13** [comment]
Why are imports inside the function in sim_f?

**Comment by shuds13** [comment]
I think the executors/__init__.py still needs attention. If for example you do not have "balsam-flow" installed then it will error out on 
`pkg_resources.get_distribution("balsam-flow")`
at least it does for me. The exception catches but "balsam" (as in balsam2) does not get imported.  I think the two imports need separate catches. 
Then I also wonder if conflicts are possible if both are present and imported. As they are notl separate namespaces. Both import 'balsam'. What do we want in that scenario.

**Comment by jlnav** [comment]
> Path to forces in define_apps.py will need to be ...forces_app/forces.x
> 
> Maybe balsam_forces -> forces_balsam (and same for funcx) to be consistent with others naming.

define_apps.py fixed.

So it isn't "forces" "forces" "forces" repetitively, underneath the main forces folder, thoughts on the folders just being, e.g. balsam, advanced, app, simple, funcx ?

**Comment by jlnav** [comment]
> Why are imports inside the function in sim_f?

This is an artifact of copy-pasting the funcx variant. It looks odd but I wouldn't mind keeping it as-is since in the future I'll work on an update to submit that sim_f remotely also via Balsam

**Comment by shuds13** [comment]
File "/home/shudson/libensemble/balsam2_process/libe1/libensemble/tests/scaling_tests/forces/balsam_forces/forces_simf.py", line 29, in run_forces_balsam
    workdir = "sim" + ["libE_info"]["H_rows"] + "_worker" + str(libE_info["workerID"])

**Pull request merged**
