### PR TITLE
Move scheduler options to libE_specs

### PR DESCRIPTION
**Pull request by shuds13**

### CODE REVIEW

**Comment by jmlarson1** [comment]
@shuds13 I think this looks good. I will note that it's odd that out of the 35 (!) libE_spec options, only one is called out here: 
https://libensemble--790.org.readthedocs.build/en/790/data_structures/libE_specs.html#scheduler-options

**Comment by shuds13** [comment]
>

**Comment by shuds13** [comment]
> @shuds13 I think this looks good. I will note that it's odd that out of the 35 (!) libE_spec options, only one is called out here:
> https://libensemble--790.org.readthedocs.build/en/790/data_structures/libE_specs.html#scheduler-options

You mean it links somewhere else to get the dictionary options? I didn't want to duplicate them - but we could put them there also.

**Comment by jmlarson1** [comment]
> > @shuds13 I think this looks good. I will note that it's odd that out of the 35 (!) libE_spec options, only one is called out here:
> > https://libensemble--790.org.readthedocs.build/en/790/data_structures/libE_specs.html#scheduler-options
> 
> You mean it links somewhere else to get the dictionary options? I didn't want to duplicate them - but we could put them there also.

I meant that out of all of the options, why is there only one given special treatment on this page? 
https://libensemble--790.org.readthedocs.build/en/790/data_structures/libE_specs.html#scheduler-options

**Comment by shuds13** [comment]
> I meant that out of all of the options, why is there only one given special treatment on this page?

There are two, because they are dictionaries that take their own sub-options.

**Comment by jmlarson1** [comment]
Okay. Note that 
https://libensemble--790.org.readthedocs.build/en/790/resource_manager/scheduler_module.html#resources-scheduler
says 
"Options can also be provided to the scheduler though the alloc_specs['user']['scheduler_opts'] dictionary." but I don't think that that is supported any more, right?

Also, how is `user_resources` passed to `resources.scheduler.ResourceScheduler`?

**Comment by shuds13** [comment]
>  "Options can also be provided to the scheduler though the alloc_specs['user']['scheduler_opts'] dictionary." but I don't think that that is supported any more, right?

Good catch. I screwed up my docs grep.

**Pull request merged**
