### PR TITLE
Give sim_id in libE_stats.txt

### PR DESCRIPTION
**Pull request by shuds13**
Resolving  #587

### CODE REVIEW

**Comment by shuds13** [comment]
@jlnav Do you think the static function _extract_H_ranges could drop the underscore and be public?

**Review by jlnav — APPROVED** [review]
Looks good. I may make ``extract_H_ranges()`` a separate internal helper function at some point (not on this PR), so the worker or potentially another module doesn't need to envoke the EnsembleDirectory class for logging purposes.

**Comment by jlnav** [comment]
So, ``extract_H_ranges()`` returns ranges separated by underscores. e.g. the rows 0, 1, 2, 3, 7, 8 returns ``'0-3_7-8'``. This is fine for directories, but for ``libE_stats.txt``, maybe ``0-3, 7-8`` looks better. This adjustment could be done with ``.replace('_', ', ')``, or adding a new parameter to ``extract_H_ranges`` for a separater.

**Comment by shuds13** [comment]
I think it would look better but we would need to check post processing scripts still work, if it had a space in it. Some of the plot scripts read this file. I'm inclined to think its okay as is (and also probably quite rare to have multiple ranges).

**Comment by shuds13** [comment]
Here is  a snippet from libE_stats.txt for test_uniform_sampling_with_different.py
```
Worker     1: Gen no     1: gen Time: 0.000 Start: 2021-03-01 22:22:56.174 End: 2021-03-01 22:22:56.174 Status: Not set
Worker     2: Gen no     1: gen Time: 0.001 Start: 2021-03-01 22:22:56.176 End: 2021-03-01 22:22:56.177 Status: Not set
Worker     3: Gen no     1: gen Time: 0.000 Start: 2021-03-01 22:22:56.179 End: 2021-03-01 22:22:56.179 Status: Not set
Worker     2: sim_id     5: sim Time: 0.808 Start: 2021-03-01 22:22:56.178 End: 2021-03-01 22:22:56.986 Status: Completed
Worker     1: sim_id   0-4: sim Time: 4.051 Start: 2021-03-01 22:22:56.176 End: 2021-03-01 22:23:00.227 Status: Completed
Worker     1: sim_id     6: sim Time: 0.406 Start: 2021-03-01 22:23:00.228 End: 2021-03-01 22:23:00.634 Status: Completed
Worker     1: Gen no     2: gen Time: 0.001 Start: 2021-03-01 22:23:00.638 End: 2021-03-01 22:23:00.639 Status: Not set
Worker     1: sim_id     7: sim Time: 0.806 Start: 2021-03-01 22:23:00.640 End: 2021-03-01 22:23:01.446 Status: Completed
```

The gen is just enumerating still on that worker which I don't love, but we don't know what gens have been run on other workers ( I suppose you could if the alloc func kept a count and put it in libE_info). 
Anything better than 'gen no'
Maybe "sim Time" or "gen Time" can just be Time.

**Comment by jlnav** [comment]
> The gen is just enumerating still on that worker which I don't love, but we don't know what gens have been run on other workers ( I suppose you could if the alloc func kept a count and put it in libE_info).

I'm sure we'd prefer to make this change without modifying all our allocation functions. Maybe ``gen_work()`` could either instantiate or update a count and append it to libE_info

> Anything better than 'gen no'

If anything, I like that it's the same character length as "sim_id". "gen_id" would be incorrect of course.

> Maybe "sim Time" or "gen Time" can just be Time.

Agreed.

I can open an issue for additional libE_stats improvements, unless we'd like to incorporate some of them into this PR

**Pull request merged**
