### PR TITLE
Branch for small changes to increase coverage

### PR DESCRIPTION
**Pull request by jmlarson1**

### CODE REVIEW

**Comment by jmlarson1** [comment]
@jlnav What should I think about the failing libE-simple tests? They are for the `test_uniform_sampling_with_variable_resources`. Is there a libE-supported way of clearing out the ensemble dir between runs? 

Is it possible to get a "green check" instead of a "red x" for our `develop` branch badge by not considering the "libE-complete" failures?

**Comment by jlnav** [comment]
> @jlnav What should I think about the failing libE-simple tests? They are for the `test_uniform_sampling_with_variable_resources`. 

For that test, it's puzzling since there's no other run that could've produced a 'dummy' ensemble dir, and no other process since that was local comms. I'm looking into it, but can't reproduce it so far.

> Is there a libE-supported way of clearing out the ensemble dir between runs?

There's no built-in feature, but it should be as simple as ``import shutil; shutil.rmtree(libE_specs['ensemble_dir_path'])`` in the calling script for now. I can add this feature properly soon.
 
> Is it possible to get a "green check" instead of a "red x" for our `develop` branch badge by not considering the "libE-complete" failures?

It's been a requested feature for years! https://github.com/actions/toolkit/issues/399

**Comment by jmlarson1** [comment]
> There's no built-in feature,

I thought it was possible to "allow overwrite" or "not raise error if ensemble dir is already there". Or am I imagining that?

**Comment by jlnav** [comment]
> I thought it was possible to "allow overwrite" or "not raise error if ensemble dir is already there". Or am I imagining that?

```
libE_spec_calc_dir_misc = ['ensemble_copy_back',
                           'ensemble_dir_path',
                           'use_worker_dirs']

libE_spec_sim_dir_keys = ['sim_dirs_make',
                          'sim_dir_copy_files',
                          'sim_dir_symlink_files',
                          'sim_input_dir']

libE_spec_gen_dir_keys = ['gen_dirs_make',
                          'gen_dir_copy_files',
                          'gen_dir_symlink_files',
                          'gen_input_dir']
```

This is what we've got so far. But especially for testing purposes, overwriting an ensemble dir is definitely important!

**Review by jlnav — APPROVED** [review]

**Review by shuds13 — APPROVED** [review]

**Pull request merged**
