### PR TITLE
Handling of large history arrays

### PR DESCRIPTION
**Pull request by jmlarson1**
Numpy now returns a view for the entire history array when indexing multiple fields. From the numpy [documentation:](https://numpy.org/doc/stable/user/basics.rec.html#accessing-multiple-fields)

>  Note that unlike for single-field indexing, the dtype of the view has the same itemsize as the original array, and has fields at the same offsets as in the original array, and unindexed fields are merely missing.
 
So an object the size of the entire history is communicate every time we send multiple fields. This can be slow (or prohibitive) when the history is large, we could send a sequence of single-fields out of the history. Or we can apply the [repack_fields](https://numpy.org/doc/stable/user/basics.rec.html#numpy.lib.recfunctions.repack_fields) option.

- A downside of this option is that it creates a structure containing copy of the fields to be sent. 
- A downside of a sequence of single-field sends is the communication cost. 

I vote for the copy approach, which is what will be in this pull request.

### CODE REVIEW

**Review by jlnav — APPROVED** [review]
Approved. Maybe I misunderstand, but communicating each field individually would _also_ produce new-structure overhead besides the communication costs, right?

**Comment by jmlarson1** [comment]
I'm not sure, but I thought that we could communicate `H['x']` without having the view of the entire `H`. The problem before was we were communicating `H[['x']]` and that inside list meant we got a full view of `H`. But I assume the local copy of `H` on the manager will be faster than the multiple communications.

**Comment by shuds13** [comment]
I agree that using repack_fields is the better solution which should then do the same as numpy 1.15 behavour. Note that it looks like this function was only introduced in numpy 1.15, so earlier versions of numpy will not work (unless we do a version test in the code and do it conditionally).

**Comment by jmlarson1** [comment]
The last version of numpy 1.14 was released in 2018 (not that long ago). We should either do a version test in the manager for the communication or assert that numpy is >= 1.15. What do you think?

**Comment by shuds13** [comment]
I think a version check is okay. I think other than this we support quite old versions of numpy. At least in libensemble core modules.

**Comment by jmlarson1** [comment]
Great. I have attempted such an numpy version check and then check if `repack_fields` is in `dir()` before using it. Open to suggestions if this isn't the proper way to do such a check.

**Comment by shuds13** [comment]
Looks fine to me.

**Review by shuds13 — APPROVED** [review]

**Pull request merged**
