### PR TITLE
Feature/subsecond time

### PR DESCRIPTION
**Pull request by jlnav**
The Timer module now measures in milliseconds behind-the-scenes. ``libE_stats`` displays additional millisecond values for Start and End times:

``Start: 2019-12-11 10:27:50.227 End: 2019-12-11 10:27:50.733``

However, for compatibility with current timing mechanisms ``timer.elapsed``  and ``timer.total`` times are returned as seconds. If necessary, I can implement additional settings or parameters for milliseconds if we want to be more precise throughout the project.

### CODE REVIEW

**Comment by jmlarson1** [comment]
@jlnav  Is it possible to replace the two uses of `time` with `datetime`? For example, using `datetime.strftime` and `time_tuple` which should be like `time.localtime()`, see:
https://docs.python.org/3/library/datetime.html#datetime.date.timetuple

Thoughts?

**Comment by jlnav** [comment]
> @jlnav Is it possible to replace the two uses of `time` with `datetime`? For example, using `datetime.strftime` and `time_tuple` which should be like `time.localtime()`, see:
> https://docs.python.org/3/library/datetime.html#datetime.date.timetuple
> 
> Thoughts?

Good point. Fixed.

**Comment by jmlarson1** [comment]
I don't think this is working as expected. When I run, I get the following output: 

````
Worker     2: Calc     0: sim Time: 0.00 Start: 2019-12-11 00:00:00.405 End: 2019-12-11 00:00:00.406 Status: Not set
Worker     3: Calc     0: sim Time: 0.00 Start: 2019-12-11 00:00:00.406 End: 2019-12-11 00:00:00.406 Status: Not set
Worker     3: Calc     1: sim Time: 0.00 Start: 2019-12-11 00:00:00.409 End: 2019-12-11 00:00:00.409 Status: Not set
Worker     2: Calc     1: sim Time: 0.00 Start: 2019-12-11 00:00:00.408 End: 2019-12-11 00:00:00.408 Status: Not set
...
...
````
The time is not correct, and the `Status` is `Not Set` for some reason.

**Comment by shuds13** [comment]
It will be Not Set unless you are using the calc_status feature. I may be inclined to only write the milliseconds to file if run-times are smaller than some cut-off, as these lines can get very long - esp. if you include job run-times (as well as calc times).

**Comment by shuds13** [comment]
I'm also getting milliseconds only on my laptop (running forces test).

**Comment by jlnav** [comment]
Sorry about that. I think I just fixed the milliseconds-only issue.

**Comment by shuds13** [comment]
Yes, the time issue seems to be fixed now.

**Pull request merged**
