### PR TITLE
Feature/restructure mpi executor

### PR DESCRIPTION
**Pull request by shuds13**
Major restructure of MPI executor.

- Create MPIRunner class with information for each type of MPI Runner and allow custom
- Move to method 2 for portable options with jsrun (num_procs -> resource sets)
- Parses extra_args for recognized no. procs/nodes/ppn options for auto-resources
- Add customizable system settings (custom_info option)

### CODE REVIEW

**Comment by jmlarson1** [comment]
> Looks good. Are `dry_run` and `extra_args` the new user-facing additions?

I think `test` became `dry_run`

**Comment by jmlarson1** [comment]
@shuds13 Any reason for the 1.8% drop in coverage?

**Comment by shuds13** [comment]
> @shuds13 Any reason for the 1.8% drop in coverage?

Partly, I can add some tests. Also some lines to check why not covered.

**Comment by shuds13** [comment]
> Looks good. Are `dry_run` and `extra_args` the new user-facing additions?

extra_args is already there. But this will parse the node/procs configuratiom parameters.

API changes:
- dry_run was called test
- mpi_executor setup includes an option custom_info - I'll add a bit in the docs - lets you define system info which overrides auto-detected parameters.

**Comment by shuds13** [comment]
I have added testing and found a couple of minor fixes in the process.

As there is a docs branch open, I will update the docs within that to avoid conflicts

**Comment by shuds13** [comment]
I don't think either of the test failures are to do with the code. One is the timing due to virtualization on OSX, the other is an initialization error. @jmlarson1 are you OK if pull this in?

**Comment by jlnav** [comment]
> I don't think either of the test failures are to do with the code. One is the timing due to virtualization on OSX, the other is an initialization error.

These pop up occasionally. If it's any comfort, I've never seen such timing errors occur on my OSX machine, only on Travis's VMs.

**Pull request merged**
