### PR TITLE
March coverage on develop fix attempts

### PR DESCRIPTION
**Pull request by jlnav**
Do these changes fix coverage on develop?

### CODE REVIEW

**Comment by jlnav** [comment]
> ## Pull Request Test Coverage Report for [Build 2920](https://coveralls.io/builds/29129525)
> 
>     * **0** of **0**   changed or added relevant lines in **0** files are covered.
> 
>     * **1** unchanged line in **1** file lost coverage.
> 
>     * Overall coverage increased (+**64.2%**) to **95.527%**
> 
> 
> Files with Coverage Reduction 	New Missed Lines 	%
> [libensemble/resources/node_resources.py](https://coveralls.io/builds/29129525/source?filename=libensemble%2Fresources%2Fnode_resources.py#L25) 	1 	79.2%
> Totals 	[Coverage Status](https://coveralls.io/builds/29129525)
> Change from base [Build 2900](https://coveralls.io/builds/29084942): 	64.2%
> Covered Lines: 	4035
> Relevant Lines: 	4185
> ##### 💛 - [Coveralls](https://coveralls.io)

Apparently yes, for some reason.

**Comment by jlnav** [comment]
If I make any progress on the Intel MKL issue #376 those commits will appear here.

**Comment by jmlarson1** [comment]
Can we pull this branch into develop first?

**Comment by jlnav** [comment]
> Can we pull this branch into develop first?

I don't know the consequences on develop besides tests and coverage for reverting @shuds13 's change, so if anything I recommend either branching off this branch or branching off develop then making the simple change. Thoughts?

**Comment by jmlarson1** [comment]
We tried to remove the `-e` so that builds on Travis would error if forgot to add all of the dependencies. But given that our coverage fails, let's just add back the `-e` until we find a better solution.

**Comment by jlnav** [comment]
> We tried to remove the `-e` so that builds on Travis would error if forgot to add all of the dependencies. But given that our coverage fails, let's just add back the `-e` until we find a better solution.

Understood!

**Pull request merged**
