### PR TITLE
Release v0.6.0

### PR DESCRIPTION
**Pull request by shuds13**
Pull request for Release v0.6.0

### CODE REVIEW

**Comment by jmlarson1** [comment]
I'll check this tomorrow, feel free to check my (slight) changes in PR #311

**Comment by shuds13** [comment]
Theres been quite a few changes since original request. Are we OK to go now? Jeff, have you checked pdf?

 @jmlarson1 @jlnav

**Comment by shuds13** [comment]
Has something gone wrong with the formatting at top of the sine tutorial?
https://libensemble.readthedocs.io/en/develop/tutorials/local_sine_tutorial.html

**Comment by jlnav** [comment]
> Has something gone wrong with the formatting at top of the sine tutorial?
> https://libensemble.readthedocs.io/en/develop/tutorials/local_sine_tutorial.html

I have no additional changes. I think the formatting was altered by moving parts of each list-line to the next line to account for line-lengths. This should probably be switched back.

**Comment by jmlarson1** [comment]
@shuds13 I just checked the diff of the pdfs between 04e303c (when the version number was set to 0.6.0) and 9a3d36a (the latest). 

There have not been formatting errors. 

I will make no further changes to develop.

**Comment by wildsm** [comment]
Neither will I.

On 12/4/19 1:01 PM, Jeffrey Larson wrote:

@shuds13<https://github.com/shuds13> I just checked the diff of the pdfs between 04e303c<https://github.com/Libensemble/libensemble/commit/04e303cb0910751d54285618f8b973abfa865a60> (when the version number was set to 0.6.0) and 9a3d36a<https://github.com/Libensemble/libensemble/commit/9a3d36a3eda9f70f975e6d6a83cba6ec52d06f4d> (the latest).

There have not been formatting errors.

I will make no further changes to develop.

**Pull request merged**
