### PR TITLE
bump pydantic versions, really trying to resolve warnings

### PR DESCRIPTION
**Pull request by jlnav**
Tries to address #1404

### CODE REVIEW

**Comment by jlnav** [comment]
orm_mode culprit: https://github.com/search?q=repo%3Aargonne-lcf%2Fbalsam%20orm_mode&type=code

root_validator culprit: https://github.com/search?q=repo%3Aargonne-lcf%2Fbalsam+%40root_validator&type=code

**Comment by jlnav** [comment]
Seems to me that to test Balsam, to avoid the warnings we should only install it on the pydantic 1 jobs

**Review by shuds13 — COMMENTED** [review]
This seems to only be changing what we test?

**Review by shuds13 — APPROVED** [review]
If the change is just only installing balsam with pydantic 1 testing, as its not compatible with pydantic 2, I approve.

**Comment by jlnav** [comment]
Basically yeah, all I did was bump Pydantic versions then only install Balsam on Pydantic 1. It'll get tested on the Pydantic 1 jobs

**Pull request merged**
