### PR TITLE
Feature/auto resources test

### PR DESCRIPTION
**Pull request by shuds13**
Job controller test uses auto_resources if enough cores available and on mpi or local comms.

### CODE REVIEW

**Comment by jmlarson1** [comment]
I'm confused by the usage of `is_master` (which is `True` for all workers) when launching with `tcp` or `local`. 

I have even received an occasional error with output being blocked when all `tcp` workers try to print at the same time.

**Comment by jmlarson1** [comment]
I'm not sure that this issue is just because of `is_master` being true. Are multiple workers trying to write to the same file at the same time:
````
[jlarson@x1carbon regression_tests]$ python3 test_jobcontroller_hworld.py --comms local --nworkers 4

Cores req: 4 Cores avail: 4
  Auto_resources set to True

In get function 4
In get function 4
In get function 4
In get function 4
Job 0 still running on worker 1 ....
Job 0 still running on worker 3 ....
Job 0 still running on worker 2 ....
Job 0 still running on worker 4 ....
Job 0 still running on worker 1 ....
Job 0 still running on worker 3 ....
Job 0 still running on worker 2 ....
Job 0 still running on worker 4 ....
Job 0 still running on worker 1 ....
Job 0 still running on worker 3 ....
Job 0 still running on worker 4 ....
Job 0 still running on worker 2 ....
Job 0 killed by manager on worker 1
Job 0 done on worker 1
Job 0 killed by manager on worker 3
Job 0 done on worker 3
Job 0 killed by manager on worker 4
Job 0 done on worker 4

Termination due to elapsed_wallclock_time has occurred.
A last attempt has been made to receive any completed work.
Posting nonblocking receives and kill messages for all active workers.


libEnsemble manager total time: 15.000256299972534

---- Received error message from 2 ----
Message: [Errno 11] write could not complete without blocking
Traceback (most recent call last):
  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 264, in run
    response = self._handle(Work)
  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 235, in _handle
    calc_out, persis_info, calc_status = self._handle_calc(Work, calc_in)
  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 176, in _handle_calc
    out = calc(calc_in, Work['persis_info'], Work['libE_info'])
  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 120, in run_sim
    return sim_f(calc_in, persis_info, sim_specs, libE_info)
  File "/home/jlarson/research/libensemble/libensemble/sim_funcs/job_control_hworld.py", line 91, in job_control_hworld
    job, calc_status = polling_loop(comm, jobctl, job, timeout)
  File "/home/jlarson/research/libensemble/libensemble/sim_funcs/job_control_hworld.py", line 33, in polling_loop
    print('Job {} still running on worker {} ....'.format(job.id, jobctl.workerID))
BlockingIOError: [Errno 11] write could not complete without blocking

--------


Manager exception raised .. aborting ensemble:


Dumping ensemble history with 0 sims evaluated:

Traceback (most recent call last):
  File "test_jobcontroller_hworld.py", line 90, in <module>
    libE_specs=libE_specs)
  File "/home/jlarson/research/libensemble/libensemble/libE.py", line 143, in libE
    persis_info, alloc_specs, libE_specs, H0)
  File "/home/jlarson/research/libensemble/libensemble/libE.py", line 296, in libE_local
    on_cleanup=cleanup)
  File "/home/jlarson/research/libensemble/libensemble/libE.py", line 154, in libE_manager
    exit_criteria, persis_info, wcomms)
  File "/home/jlarson/research/libensemble/libensemble/libE_manager.py", line 49, in manager_main
    return mgr.run(persis_info)
  File "/home/jlarson/research/libensemble/libensemble/libE_manager.py", line 330, in run
    persis_info = self._receive_from_workers(persis_info)
  File "/home/jlarson/research/libensemble/libensemble/libE_manager.py", line 232, in _receive_from_workers
    self._handle_msg_from_worker(persis_info, w)
  File "/home/jlarson/research/libensemble/libensemble/libE_manager.py", line 286, in _handle_msg_from_worker
    D_recv.msg, D_recv.exc)
libensemble.libE_manager.ManagerException: ('Received error message from 2', '[Errno 11] write could not complete without blocking', 'Traceback (most recent call last):\n  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 264, in run\n    response = self._handle(Work)\n  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 235, in _handle\n    calc_out, persis_info, calc_status = self._handle_calc(Work, calc_in)\n  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 176, in _handle_calc\n    out = calc(calc_in, Work[\'persis_info\'], Work[\'libE_info\'])\n  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 120, in run_sim\n    return sim_f(calc_in, persis_info, sim_specs, libE_info)\n  File "/home/jlarson/research/libensemble/libensemble/sim_funcs/job_control_hworld.py", line 91, in job_control_hworld\n    job, calc_status = polling_loop(comm, jobctl, job, timeout)\n  File "/home/jlarson/research/libensemble/libensemble/sim_funcs/job_control_hworld.py", line 33, in polling_loop\n    print(\'Job {} still running on worker {} ....\'.format(job.id, jobctl.workerID))\nBlockingIOError: [Errno 11] write could not complete without blocking\n')
````

**Comment by shuds13** [comment]
I'm not sure what you mean? In local mode, the workers do not exist at that point, in tcp mode it should be correct. Are you getting the error on the print I added to this test?

**Comment by jmlarson1** [comment]
Yes, I think that error comes from threads trying to write at the same time. I was getting a similar error from everyone writing the USER_SIM_ID_WARNING within check_inputs. (I'm in the process of moving that on a different branch.)

Does the above error for threads all writing at the same time need to be addressed?

**Comment by shuds13** [comment]
I'm looking into it. It may be due to IOBlocking mode in your environment, I need to quickly revise that. Also getting rid of the old "In get function" print. That shouldn't be there.

**Comment by shuds13** [comment]
Can you see if this makes a difference?
import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)

from https://github.com/travis-ci/travis-ci/issues/8920

**Comment by jmlarson1** [comment]
I'm unable to recreate the issue with or without that line at the top of `test_jobcontroller_hworld.py`.

It's intermittent, so I'm not sure it is fixed.

**Pull request merged**
