### PR TITLE
Feature / Request History options

### PR DESCRIPTION
**Pull request by jlnav**
Addresses #1103 

New options plus their defaults:

```
    save_H_on_completion: Optional[bool] = False
    """ Save state of ``H`` to file upon completing a workflow."""

    save_H_with_date: Optional[bool] = False
    """ ``H`` filename contains date and timestamp."""

    H_file_prefix: Optional[str] = "libE_history"
    """ Prefix for ``H`` filename."""
```

### CODE REVIEW

**Review by AngelFP — COMMENTED** [review]
Thanks for this @jlnav!
I have given it a try and it works very well. There's only an additional comment I have, which is that the file saved on completion has a different name than those saved every k steps. Ideally this wouldn't be the case, because then we always have two history files after an optimas run (i.e., `exploration_history_after_sim_20.npy` and `exploration_history_after_completion.npy`).

One possible solution that I see would be a final call to
```python
if self.libE_specs.get("save_every_k_sims"):
    self._save_every_k_sims()
if self.libE_specs.get("save_every_k_gens"):
    self._save_every_k_gens()
```
if `"save_H_on_completion"` is enabled. This would probably require a `force=True` argument in `_save_every_k` to make sure that the final history is saved.

**Comment by jlnav** [comment]
> Thanks for this @jlnav! I have given it a try and it works very well. There's only an additional comment I have, which is that the file saved on completion has a different name than those saved every k steps. Ideally this wouldn't be the case, because then we always have two history files after an optimas run (e.g., `exploration_history_after_sim_20.npy` and `exploration_history_after_completion.npy`).
> 
> One possible solution that I see would be a final call to
> 
> ```python
> if self.libE_specs.get("save_every_k_sims"):
>     self._save_every_k_sims()
> if self.libE_specs.get("save_every_k_gens"):
>     self._save_every_k_gens()
> ```
> 
> if `"save_H_on_completion"` is enabled. This would probably require a `force=True` argument in `_save_every_k` to make sure that the final history is saved.

Sounds good, thanks! I can make that change right away.

**Review by AngelFP — APPROVED** [review]
Works great now :D

**Comment by shuds13** [comment]
If save_H_on_completion defaults to True, what stops you from getting two .npy files at the end, when user is dumping their file already?

**Review by shuds13 — APPROVED** [review]

**Pull request merged**
