### PR TITLE
isort entire repository!

### PR DESCRIPTION
**Pull request by jlnav**
And I don't think flake8 broke, at least locally?

### CODE REVIEW

**Comment by jmlarson1** [comment]
@jlnav Can we please add `isort` (and `black`) to the required tests for PRs to develop?

**Comment by jlnav** [comment]
> @jlnav Can we please add isort (and black) to the required tests for PRs to develop?

Just to clarify, you're asking for `black --check` and `isort --check`?

Now that we're up to three tools that will fail PRs if they're not all run, it may be worth investigating either PR bots to run black and isort on the PR code, or:

https://pre-commit.com/

Which can be configured to run those utilities automatically on your machine whenever you commit

**Comment by jmlarson1** [comment]
I'm fine with either have PR bots run or having precommit hooks. What's easiest to set up?

**Comment by jlnav** [comment]
Honestly, probably each of us installing pre-commit, but first I'll make a PR to set up the repo properly (adding a `.pre-commit-config.yaml`)

**Pull request closed without merging**
