### PR TITLE
Feature / any calc status

### PR DESCRIPTION
**Pull request by jlnav**
Addresses #808 

Simple enough series of adjustments so users can return whatever they'd like for a calc status to log into libE_stats.

_However!_ This isn't supported for persistent functions because of (at a minimum, and probably elsewhere too)
logic in ``_update_state_on_worker_msg()``. So custom calc statuses will likely only be used within common sim_fs.

### CODE REVIEW

**Comment by jmlarson1** [comment]
In this branch, can we group the entries in `libensemble/message_numbers.py` to those that are calc_statuses, as opposed to other types of message numbers?

**Comment by jlnav** [comment]
Should this be going into the release branch instead?

**Comment by jmlarson1** [comment]
> Should this be going into the release branch instead?

Everything has been going into `develop`. After it's pulled in, I just pull into the release then delete the branch (without waiting for all tests to pass).

I'm open to any procedure.

**Review by jmlarson1 — APPROVED** [review]

**Comment by shuds13** [comment]
Has docs/data_structures/calc_status.rst been updated?

**Review by shuds13 — APPROVED** [review]

**Pull request merged**
