### PR TITLE
Allowing to users to tell the manager to not check whether to cancel …

### PR DESCRIPTION
**Pull request by jmlarson1**
…points

### CODE REVIEW

**Review by shuds13 — COMMENTED** [review]
I'm wondering if check_cancel is best term.

Its really about whether it sends out a kill signal to cancelled sims. Maybe more like 'kill_cancelled', or something better?

**Comment by jmlarson1** [comment]
@shuds13 The intention is to not even check if any user function has requested a cancel if `check_cancel` is False. For fast sim_f evaluation times and long runs, the check
````
kill_sim = self.hist.H['given'] & self.hist.H['cancel_requested'] \
                & ~self.hist.H['returned'] & ~self.hist.H['kill_sent']
````
becomes a major bottleneck in the manager. 

Related (but a different PR) would be finding is a more intelligent way of doing that check. For a `sim_id` that is `returned`, we won't be sending a kill.

**Comment by shuds13** [comment]
I planned to include the sliding window approach in this check (and anything that did a whole of H filter), when possible. But even still that whole block of code is deciding whether to send a kill. If a sim is cancelled before being sent out, it will not be sent by the allocation function, and so I don't want to confuse with that check.

**Comment by jmlarson1** [comment]
> If a sim is cancelled before being sent out, it will not be sent by the allocation function, and so I don't want to confuse with that check.

Wouldn't it have to be the user function that cancels a sim before being sent out?

**Comment by shuds13** [comment]
Yes, user function sets cancel_requested.

**Comment by shuds13** [comment]
I also wonder if there should be a compound option to make everything as fast as possible in this respect - eg. dont check safe mode, dont check/send kills

**Comment by jmlarson1** [comment]
So I'd like to make a boolean that would tell the manager not to check if any cancel has been requested. I thought `libE_specs['check_cancel']` was an okay name. Any suggestions for something better?

**Comment by shuds13** [comment]
I suggest kill_cancelled_sims
I've add this to the terminology wiki https://github.com/Libensemble/libensemble/wiki/Terminology-structure-decisions

**Review by shuds13 — APPROVED** [review]

**Pull request merged**
