### PR TITLE
Experimental/simgendir restructure

### PR DESCRIPTION
**Pull request by jlnav**
New features, dramatic refactoring and new functionality for simulation-directory creation. Primarily, by default output directory copies are now _per-simulation_. Which files are copied or symlinked from the input directory can be specified in `libE_specs`. By default, all output directories are placed in an "ensemble" directory.

In regards to already-existing options:

- `sim_dir` is renamed `sim_input_dir`.
- `sim_dir_prefix` is renamed `ensemble_dir`. The default output directory is `./ensemble` and can be renamed using this setting.
- `sim_dir_suffix` is renamed `ensemble_dir_suffix`. This option can help users differentiate their output directories however they choose (maybe this is now redundant?).
- `clean_jobs` is renamed `clean_ensemble_dirs`.

In regards to new options:

- `use_worker_dirs`: Boolean. Organize each simulation directory into per-worker parent directories.
- `copy_input_files`: List of strings. Filenames from the input directory to copy over, and ignore the others. If not specified, all files from the input directory are copied.
- `symlink_input_files`: List of strings. Out of all the files copied over from the input directory, create symbolic links to these files instead.
- `copy_input_to_parent`: Boolean. Copy **all** files in the input directory to whichever directories directly contain the simulation directories (if `use_worker_dirs` is True, that would be every worker directory. Otherwise, directly within the ensemble directory). If used with `symlink_input_files`, the symbolic links will point to these close-by copies instead of those in the input directory.

For more information, please read the documentation I wrote in `history_output.rst`. To try out these features, please look at the `test_worker_sim_dirs.py` regression test and the Forces example.

As usual, feedback is greatly appreciated.

### CODE REVIEW

**Comment by shuds13** [comment]
This is looking good. I think in the case of using scratch, we should have the option to copy back to the central location. As this is not done currently, and it can be done manually by the user, I'm happy if you want to seperate that task - but we should run on Bebop, using scratch, to ensure nothings broken.

How is the state of testing on this? Are the different scenarios covered by unit/regression tests?

**Comment by jlnav** [comment]
> This is looking good. I think in the case of using scratch, we should have the option to copy back to the central location. As this is not done currently, and it can be done manually by the user, I'm happy if you want to seperate that task - but we should run on Bebop, using scratch, to ensure nothings broken.
> 
> How is the state of testing on this? Are the different scenarios covered by unit/regression tests?

1) Sounds good. I would probably prefer to separate that feature into another branch since this one has been open and worked on for a while. Should we test on Bebop without that feature anyway, just to make sure that output really can be directed to ``/scratch``? 

2) Admittedly, the tests only determine currently that the correct numbers of directories are being created. I'll add checks for more conditions.

**Comment by shuds13** [comment]
Yes to 1. Can you test it on Bebop, maybe using the forces example.

**Comment by jlnav** [comment]
Changes:

- Regression test ``test_worker_sim_dirs.py`` is much more comprehensive.
- ``loc_stack.py`` should no longer skip copying groups of files if one already exists in a destination.
- New approaches to reduce predictable and redundant error-handling (typically when copying or deleting files).

**Comment by jlnav** [comment]
### Bebop Testing since 1/14

Combinations of the following choices all need to work:
- Running in **Centralized** or **Distributed** Mode
- Writing output to **per-node** or **global** scratch space
- Write calculation directories into **worker-directories** or **a single directory**.

For a total of eight different plausible configuration modes.

### Centralized Testing:

- [ ] Per-node Scratch / Single directory:
Although all workers can presumably access the same scratch space, other workers besides 1 can't change to ``/scratch``. Receive following errors:
```
$ cat sim*/err.txt
slurmstepd: error: couldn't chdir to `/scratch/libE_forces_out_11:15:06/sim1-worker2': No such file or directory: going to /tmp instead
slurmstepd: error: couldn't chdir to `/scratch/libE_forces_out_11:15:06/sim2-worker3': No such file or directory: going to /tmp instead
slurmstepd: error: couldn't chdir to `/scratch/libE_forces_out_11:15:06/sim3-worker4': No such file or directory: going to /tmp instead
```

- [ ] Per-node Scratch / Worker directories:

- [x] Global Scratch / Single directory:
Appears to work perfectly.

- [ ] Global Scratch / Worker directories:

### Distributed Testing:

- [ ] Per-node Scratch / Single directory:

- [ ] Per-node Scratch / Worker directories:

- [ ] Global Scratch / Single directory:
Only simulations completed by worker 1 are found in the ensemble directory.

- [ ] Global Scratch / Worker directories:

**Comment by jlnav** [comment]
> I'm okay with pulling this into develop.

Sounds good. I'll be most comfortable pulling this in once we've got our common use-case configurations working on Bebop.

**Comment by jlnav** [comment]
### Bebop Testing since 1/22

The basic combination of settings:
```
libE_specs['sim_input_dir'] = './sim'
libE_specs['ensemble_dir'] = '/scratch/libE_ensemble'
libE_specs['use_worker_dirs'] = True
libE_specs['copy_back_output'] = True
```
is now confirmed to work in Centralized mode if using global scratch spaces, and Distributed mode for both global and local scratch spaces.

The following settings need to be tested:

```
libE_specs['copy_input_files'] = ['copy_this']
libE_specs['symlink_input_files'] = ['symlink_this']
libE_specs['copy_input_to_parent'] = True
```

### Centralized Testing:

- [] Global Scratch / Single directory:


- [] Global Scratch / Worker directories:


### Distributed Testing:

- [] Per-node Scratch / Single directory:


- [] Per-node Scratch / Worker directories:


- [] Global Scratch / Single directory:


- [] Global Scratch / Worker directories:

**Comment by jlnav** [comment]
Testing on Bebop is complete. Centralized mode is supported if using global filesystems or scratch spaces as the workers' working directory. In distributed mode, both global and local scratch spaces are supported, as long as libE is initially launched from a global location (so each worker as a common location to copy back to).

**Pull request merged**
